on:
  push:
    branches: [ "main" ] 

jobs: 
  deploy:
    runs-on: ubuntu-latest
   # needs: [sonar_scan, security-check, build_docker_image_and_push]
    steps:
      - name: SSH into EC2 and Deploy Docker Containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "🔹 Installing Docker on EC2..."
            # Install Docker if it's not already installed
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl enable --now docker
            else
              echo "Docker is already installed."
            fi
  
            # Running MongoDB container
            echo "🔹 Running MongoDB container..."
            sudo docker run -d --name mongodb -p 27017:27017 mongo
  
            # Running Food Donation App container
            echo "🔹 Running Food Donation App container..."
            sudo docker run -d --name food-donation-app --link mongodb:mongo --env-file .env -p 5000:5000 rocks3/feeding-hope:latest
  
            # Running Prometheus container
            echo "🔹 Running Prometheus container..."
            sudo docker run -d \
              --name prometheus \
              -p 9090:9090 \
              -v /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml \
              prom/prometheus
  
            # Running Node Exporter to monitor EC2 instance
            echo "🔹 Running Node Exporter for EC2 monitoring..."
            sudo docker run -d \
              --name node-exporter \
              -p 9100:9100 \
              prom/node-exporter
  
            # Running Grafana container
            echo "🔹 Running Grafana container..."
            sudo docker run -d \
              --name grafana \
              -p 3000:3000 \
              --link prometheus:prometheus \
              -e GF_SECURITY_ADMIN_PASSWORD=admin \
              grafana/grafana

            echo "🔹 Deployment complete!"
