name: CICD Pipeline 

on:
  push:
    branches: [ "main" ] 
 
jobs: 
 
  deploy:
    runs-on: ubuntu-latest
   # needs: [sonar_scan, security-check,build_docker_image_and_push]  # Deploy only if SonarQube & Prometheus checks pass 
    steps:
      - name: SSH into EC2 and Deploy Docker Containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "🔹 Installing Docker on EC2..."
            # Install Docker if it's not already installed
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl enable --now docker
            else
              echo "Docker is already installed."
            fi
  
            echo "🔹 Creating .env file for MongoDB URI..."
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            
            echo "🔹 Starting MongoDB container..."
            sudo docker run -d --name mongodb -p 27017:27017 mongo
  
            echo "🔹 Starting Food Donation App container..."
            sudo docker run -d --name food-donation-app --link mongodb:mongo --env-file .env -p 5000:5000 rocks3/feeding-hope:latest
  
            echo "🔹 Deployment complete!"
